// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjrkeshwgjcoeswjqbhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcmtlc2h3Z2pjb2Vzd2pxYmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5Mzk0ODAsImV4cCI6MjA2MTUxNTQ4MH0.EdyOX2F-O9a2mwQ8JkmwG8u6KsONgESDi9hfn2vdlEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);